export const RES_MSG = {
    /** COMMON TYPE MSG */
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    INPUT_TYPE_ERROR: 'INPUT_TYPE_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',

    /** DOMAIN MSG */
    IS_NOT_VALID_PAYMENT_TOKEN: 'IS_NOT_VALID_PAYMENT_TOKEN',
    HAS_NOT_PAYMENT_TOKEN: 'HAS_NOT_PAYMENT_TOKEN',
    SET_PAYMENT_TOKEN_SUCCESS: 'SET_PAYMENT_TOKEN_SUCCESS',
    SET_PAYMENT_TOKEN_FAILURE: 'SET_PAYMENT_TOKEN_FAILURE',
    SET_PAYMENT_TOKEN_STATUS_SUCCESS: 'SET_PAYMENT_TOKEN_STATUS_SUCCESS',
    SET_PAYMENT_TOKEN_STATUS_FAILURE: 'SET_PAYMENT_TOKEN_STATUS_FAILURE',

    LOAD_PRODUCT_SUCCESS: 'LOAD_PRODUCT_SUCCESS',
    LOAD_PRODUCT_FAILURE: 'LOAD_PRODUCT_FAILURE',

    HAS_NOT_USER_ACCOUNT: 'HAS_NOT_USER_ACCOUNT',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

    CREATE_ACCOUNT_INPUT_ERROR: 'CREATE_ACCOUNT_INPUT_ERROR',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',

    IS_NOT_AVAILABLE_FOR_ORDER: 'IS_NOT_AVAILABLE_FOR_ORDER',
    IS_INSUFFICIENT_PAY_POINT: 'IS_INSUFFICIENT_PAY_POINT',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GENERATE_PAYMENT_TOKEN_SUCCESS: 'GENERATE_PAYMENT_TOKEN_SUCCESS',
    GENERATE_PAYMENT_TOKEN_FAILURE: 'GENERATE_PAYMENT_TOKEN_FAILURE',

    EDIT_USER_INPUT_ERROR: 'EDIT_USER_INPUT_ERROR',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

    JOIN_USER_INPUT_ERROR: 'JOIN_USER_INPUT_ERROR',
    JOIN_USER_DUPLICATE_EMAIL: 'JOIN_USER_DUPLICATE_EMAIL',
    JOIN_USER_SUCCESS: 'JOIN_USER_SUCCESS',
    JOIN_USER_FAILURE: 'JOIN_USER_FAILURE',

    IS_ALREADY_LOGIN: 'IS_ALREADY_LOGIN',
    IS_NOT_MATCH_EMAIL_OR_PASSWORD: 'IS_NOT_MATCH_EMAIL_OR_PASSWORD',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
} as const

export type RES_MSG_TYPE = (typeof RES_MSG)[keyof typeof RES_MSG]

export const isResMsgType = (resMsg: any): resMsg is RES_MSG_TYPE => {
    return Object.values(RES_MSG).includes(resMsg)
}

export const BANK = ['국민은행', '신한은행', '토스뱅크'] as const

export type Bank = (typeof BANK)[number]

export const PAYMENT_TOKEN_EXPIRATION = 15 * 60 * 1000
