export const RES_MSG = {
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    INPUT_TYPE_ERROR: 'INPUT_TYPE_ERROR',

    EDIT_USER_INPUT_ERROR: 'EDIT_USER_INPUT_ERROR',
    CREATE_USER_INPUT_ERROR: 'CREATE_USER_INPUT_ERROR',
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',

    IS_NOT_MATCH: 'IS_NOT_MATCH',

    IS_NOT_VALID_PAYMENT_TOKEN: 'IS_NOT_VALID_PAYMENT_TOKEN',

    IS_NOT_AVAILABLE_FOR_ORDER: 'IS_NOT_AVAILABLE_FOR_ORDER',

    LOAD_PRODUCT_SUCCESS: 'LOAD_PRODUCT_SUCCESS',
    LOAD_PRODUCT_FAILURE: 'LOAD_PRODUCT_FAILURE',

    HAS_NOT_USER_ACCOUNT: 'HAS_NOT_USER_ACCOUNT',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

    CREATE_ACCOUNT_INPUT_ERROR: 'CREATE_ACCOUNT_INPUT_ERROR',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',
} as const

export type RES_MSG_TYPE = (typeof RES_MSG)[keyof typeof RES_MSG]

export const isResMsgType = (resMsg: any): resMsg is RES_MSG_TYPE => {
    return Object.values(RES_MSG).includes(resMsg)
}

export const BANK = ['국민은행', '신한은행', '토스뱅크'] as const

export type Bank = (typeof BANK)[number]

export const PAYMENT_TOKEN_EXPIRATION = 15 * 60 * 1000
